Apache

diff --git a/loops_conditions_and_parsing/14-dig_the-data b/loops_conditions_and_parsing/14-dig_the-data
--- a/loops_conditions_and_parsing/14-dig_the-data
+++ b/loops_conditions_and_parsing/14-dig_the-data
@@ -1,4 +1,7 @@
 #!/usr/bin/env bash
 #groups visitors IP and HTTP status code and displays this data
-
-awk '{print $1,$9}' apache-acess.log | sort | uniq -c | sort -nr
+if [ ! -f "apache-access.log" ]; then
+	echo "Error: File apache-access.log does not exist."
+	exit 1
+fi
+awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr
